"use client";

import { useState, useMemo } from "react";
import { useNeoFlow } from "@/lib/store";
import { fetchGeminiAiAdvice } from "@/lib/gemini-ai";
import { GlassCard } from "@/components/glass-card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Brain,
  Sparkles,
  Zap,
  TrendingUp,
  Target,
  Flame,
  CheckCircle2,
  Lightbulb,
  Send,
  Bot,
  ArrowRight,
  ShieldCheck,
  Plus,
  Calendar as CalendarIcon,
  Check,
  Cpu,
} from "lucide-react";
import { type AiStrategyResponse } from "@/lib/gemini-ai";
import { cn } from "@/lib/utils";
import { cppEngine } from "@/lib/cpp-engine-adapter";

type InsightCategory = "overview" | "priority" | "streaks" | "tips";

export function SmartFocusEngine() {
  const { plans, tasks, financialGoals, savedAmount, transactions, addPlan, addTask } = useNeoFlow();
  const [activeTab, setActiveTab] = useState<InsightCategory>("overview");
  const [userQuery, setUserQuery] = useState("");
  const [isThinking, setIsThinking] = useState(false);
  const [customResponse, setCustomResponse] = useState<AiStrategyResponse | null>(null);
  const [createdNotice, setCreatedNotice] = useState<string | null>(null);

  const handleAutoCreatePlan = (res: AiStrategyResponse) => {
    addPlan({
      title: res.suggestedTitle || "New Habit Plan",
      category: res.category || "skill",
      description: res.suggestedDescription || "Auto-generated by AI Co-Pilot",
      deadline: new Date(Date.now() + 14 * 86400000).toISOString(),
      progress: 0,
    });

    if (typeof window !== "undefined") {
      try {
        const audioCtx = new (window.AudioContext || (window as any).webkitAudioContext)();
        const osc = audioCtx.createOscillator();
        const gain = audioCtx.createGain();
        osc.type = "sine";
        osc.frequency.setValueAtTime(523.25, audioCtx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(880.0, audioCtx.currentTime + 0.3);
        gain.gain.setValueAtTime(0.12, audioCtx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.01, audioCtx.currentTime + 0.4);
        osc.connect(gain);
        gain.connect(audioCtx.destination);
        osc.start();
        osc.stop(audioCtx.currentTime + 0.4);
      } catch {}
    }

    setCreatedNotice(`Created Active Plan: "${res.suggestedTitle}"`);
    setTimeout(() => setCreatedNotice(null), 4000);
  };

  const handleAutoCreateTask = (res: AiStrategyResponse) => {
    const subtasks = (res.suggestedSubtasks || ["Step 1", "Step 2"]).map((st, i) => ({
      id: `${Date.now()}-${i}`,
      title: st,
      completed: false,
    }));

    addTask({
      title: res.suggestedTitle || "New Task",
      priority: res.priority || "high",
      status: "todo",
      deadline: new Date(Date.now() + 24 * 3600000).toISOString(),
      subtasks,
    });

    if (typeof window !== "undefined") {
      try {
        const audioCtx = new (window.AudioContext || (window as any).webkitAudioContext)();
        const osc = audioCtx.createOscillator();
        const gain = audioCtx.createGain();
        osc.type = "sine";
        osc.frequency.setValueAtTime(659.25, audioCtx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(987.77, audioCtx.currentTime + 0.3);
        gain.gain.setValueAtTime(0.12, audioCtx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.01, audioCtx.currentTime + 0.4);
        osc.connect(gain);
        gain.connect(audioCtx.destination);
        osc.start();
        osc.stop(audioCtx.currentTime + 0.4);
      } catch {}
    }

    setCreatedNotice(`Created Priority Task: "${res.suggestedTitle}"`);
    setTimeout(() => setCreatedNotice(null), 4000);
  };

  // Calculate Real-time Productivity Index (0-100) using C++ Engine Optimization
  const stats = useMemo(() => {
    const totalTasks = tasks.length;
    const completedTasks = tasks.filter((t) => t.status === "done").length;
    
    // C++ Engine Focus Stats computation
    const focusStats = cppEngine.computeFocusStats(completedTasks * 25, 10, 0);

    const totalPlans = plans.length;
    const avgProgress = totalPlans > 0 ? plans.reduce((acc, p) => acc + p.progress, 0) / totalPlans : 50;
    const planPoints = (avgProgress / 100) * 30;

    const totalCheckins = plans.reduce((acc, p) => {
      const active = Object.values(p.dailyCheckins || {}).filter((v) => v === true).length;
      return acc + active;
    }, 0);
    const streakPoints = Math.min(20, totalCheckins * 4);

    const productivityIndex = Math.min(100, Math.round((focusStats.focusEfficiencyScore * 0.5) + planPoints + streakPoints));

    // C++ Engine Task Prioritization
    const prioritizedTasksList = cppEngine.prioritizeTasks(
      tasks.map((t) => ({
        id: t.id,
        priority: t.priority,
        isCompleted: t.status === "done",
        estimatedMinutes: 30,
        daysUntilDue: Math.max(0, Math.ceil((new Date(t.deadline).getTime() - Date.now()) / 86400000)),
      }))
    );

    const topPrioritizedId = prioritizedTasksList[0]?.id;
    const topUrgentTask = tasks.find((t) => t.id === topPrioritizedId) || tasks.find((t) => t.status !== "done");

    const today = new Date().toISOString().split("T")[0];
    const tasksDueToday = tasks.filter((t) => {
      if (t.status === "done") return false;
      const deadline = new Date(t.deadline).toISOString().split("T")[0];
      return deadline <= today;
    }).length;

    const deposits = (transactions || []).filter((tx) => tx.type === "deposit");
    const monthlySavingsRate = deposits.length > 0
      ? Math.round(deposits.slice(0, 10).reduce((s, t) => s + t.amount, 0) / Math.max(1, deposits.slice(0, 10).length) * 4)
      : 500;

    const activeGoals = financialGoals.filter((g) => !g.isPurchased);
    const totalGoalCost = activeGoals.reduce((sum, g) => sum + g.price, 0);

    return {
      productivityIndex,
      completedTasks,
      totalTasks,
      topUrgentTask,
      totalPlans,
      savedAmount,
      totalGoalCost,
      urgentTasksCount: tasks.filter((t) => t.status !== "done").length,
      tasksDueToday,
      monthlySavingsRate,
      executionTimeMs: focusStats.executionTimeMs,
    };
  }, [plans, tasks, financialGoals, savedAmount, transactions]);

  // Live AI ask handler
  const handleAiAsk = async (promptText?: string) => {
    const query = promptText || userQuery;
    if (!query || query.trim().length === 0) return;

    setIsThinking(true);
    setCustomResponse(null);

    const res = await fetchGeminiAiAdvice(query, {
      tasksCount: stats.urgentTasksCount,
      urgentTaskTitle: stats.topUrgentTask?.title,
      plansCount: stats.totalPlans,
      savedAmount: stats.savedAmount,
      totalGoalCost: stats.totalGoalCost,
      productivityIndex: stats.productivityIndex,
      tasksDueToday: stats.tasksDueToday,
      monthlySavingsRate: stats.monthlySavingsRate,
    });

    setCustomResponse(res);
    setIsThinking(false);
  };

  // Standard tab content
  const insightContent = useMemo(() => {
    switch (activeTab) {
      case "priority":
        if (stats.topUrgentTask) {
          return {
            title: `Recommended Focus: "${stats.topUrgentTask.title}"`,
            description: `Priority: ${stats.topUrgentTask.priority.toUpperCase()} | Due: ${new Date(stats.topUrgentTask.deadline).toLocaleDateString()}. Completing this will boost your Flow State Index by +12 pts.`,
            icon: Target,
            badge: "Top Priority",
            badgeColor: "bg-destructive/20 text-destructive border-destructive/30",
          };
        }
        return {
          title: "All critical tasks completed!",
          description: "Great job! Create a new task or review your active plans to maintain momentum.",
          icon: CheckCircle2,
          badge: "Clear Queue",
          badgeColor: "bg-chart-4/20 text-chart-4 border-chart-4/30",
        };

      case "streaks":
        return {
          title: `Daily Momentum: ${stats.completedTasks}/${stats.totalTasks} Tasks Done`,
          description: "Consistency builds mastery! Keep checking in daily on your active plans to boost your flow state multiplier.",
          icon: Flame,
          badge: "Active Streak",
          badgeColor: "bg-orange-500/20 text-orange-400 border-orange-500/30",
        };

      case "tips":
        return {
          title: "Genius Tip: Use the Focus Studio Pomodoro Companion",
          description: "Attach tasks directly to 25-minute deep work sessions on your dashboard to auto-complete tasks on timer finish.",
          icon: Lightbulb,
          badge: "Productivity Hack",
          badgeColor: "bg-accent/20 text-accent border-accent/30",
        };

      case "overview":
      default:
        return {
          title: `Productivity Index: ${stats.productivityIndex}% (${stats.productivityIndex >= 70 ? "Optimal Flow" : "Building Velocity"})`,
          description: stats.topUrgentTask
            ? `Next high impact move: Complete "${stats.topUrgentTask.title}"`
            : "Your schedule is clean. Take time to plan your upcoming goals!",
          icon: TrendingUp,
          badge: `${stats.productivityIndex}% Score`,
          badgeColor: "bg-secondary/20 text-secondary border-secondary/30",
        };
    }
  }, [activeTab, stats]);

  const IconComponent = insightContent.icon;

  return (
    <GlassCard glow="blue" className="relative overflow-hidden border border-primary/40 shadow-xl">
      {/* Background ambient lighting */}
      <div className="absolute -top-12 -right-12 w-56 h-56 bg-primary/20 rounded-full blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
        <div className="flex items-center gap-2.5">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary via-secondary to-accent flex items-center justify-center glow-blue shrink-0">
            <Brain className="h-5 w-5 text-white" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold gradient-text">Neo Live AI Co-Pilot</h2>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-primary/20 text-primary border border-primary/30 font-bold uppercase tracking-wider flex items-center gap-1">
                <Bot className="h-3 w-3 text-primary animate-pulse" />
                Active Intelligence
              </span>
            </div>
            <p className="text-xs text-muted-foreground flex items-center gap-1">
              <Cpu className="h-3 w-3 text-accent" />
              Real-time schedule analysis & C++ prioritization engine
            </p>
          </div>
        </div>

        {/* Productivity Score Pill */}
        <div className="flex items-center gap-2 glass px-3.5 py-1.5 rounded-xl border border-border/50 shrink-0">
          <Zap className="h-4 w-4 text-accent animate-pulse" />
          <div className="text-right">
            <div className="text-[10px] text-muted-foreground font-medium uppercase">Flow State Index</div>
            <div className="text-base font-bold text-foreground font-mono">{stats.productivityIndex}/100</div>
          </div>
        </div>
      </div>

      {/* Interactive AI Prompt Bar */}
      <div className="glass rounded-xl p-2.5 mb-4 border border-primary/30 space-y-2">
        <div className="flex gap-2">
          <Input
            value={userQuery}
            onChange={(e) => setUserQuery(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleAiAsk()}
            placeholder="Ask AI Co-Pilot (e.g. 'How to reach my $100k goal fast', 'Plan today')..."
            className="bg-muted/60 border-border/50 text-xs py-2 focus-visible:ring-1 focus-visible:ring-primary"
          />
          <Button
            onClick={() => handleAiAsk()}
            disabled={isThinking}
            className="bg-primary/20 text-primary border border-primary/40 hover:bg-primary/30 text-xs px-3.5 shrink-0 font-semibold"
          >
            {isThinking ? (
              <Sparkles className="h-4 w-4 animate-spin" />
            ) : (
              <>
                <Send className="h-3.5 w-3.5 mr-1" /> Ask AI
              </>
            )}
          </Button>
        </div>

        {/* Preset AI Quick Chips */}
        <div className="flex gap-1.5 overflow-x-auto pt-1 pb-0.5">
          <button
            onClick={() => {
              setUserQuery("How to reach my $100k savings goal fast?");
              handleAiAsk("How to reach my $100k savings goal fast?");
            }}
            className="px-2.5 py-1 rounded-lg glass text-[11px] font-medium text-accent hover:bg-accent/20 border border-accent/30 whitespace-nowrap transition-all flex items-center gap-1"
          >
            <Sparkles className="h-3 w-3" /> $100k Growth Plan
          </button>
          <button
            onClick={() => {
              setUserQuery("Generate my focus schedule for today");
              handleAiAsk("Generate my focus schedule for today");
            }}
            className="px-2.5 py-1 rounded-lg glass text-[11px] font-medium text-primary hover:bg-primary/20 border border-primary/30 whitespace-nowrap transition-all flex items-center gap-1"
          >
            <Target className="h-3 w-3" /> Today&apos;s Execution Schedule
          </button>
          <button
            onClick={() => {
              setUserQuery("How to maximize focus & clear task bottlenecks?");
              handleAiAsk("How to maximize focus & clear task bottlenecks?");
            }}
            className="px-2.5 py-1 rounded-lg glass text-[11px] font-medium text-secondary hover:bg-secondary/20 border border-secondary/30 whitespace-nowrap transition-all flex items-center gap-1"
          >
            <Zap className="h-3 w-3" /> Clear Task Bottlenecks
          </button>
        </div>
      </div>

      {/* AI Live Output Display */}
      {isThinking ? (
        <div className="glass rounded-xl p-5 border border-primary/30 text-center space-y-2">
          <div className="flex items-center justify-center gap-2 text-primary font-semibold text-sm">
            <Sparkles className="h-5 w-5 animate-spin" />
            Analyzing active tasks, deadlines, and wallet balance...
          </div>
        </div>
      ) : customResponse ? (
        <div className="glass rounded-xl p-4 border border-accent/40 space-y-2 relative animate-in fade-in duration-300">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-accent uppercase tracking-wider flex items-center gap-1.5">
              <ShieldCheck className="h-4 w-4 text-accent" />
              {customResponse.type}
            </span>
            <span className="text-[11px] font-mono font-bold px-2 py-0.5 rounded bg-accent/20 text-accent border border-accent/30">
              {customResponse.impactScore}
            </span>
          </div>

          <h3 className="font-bold text-sm text-foreground">{customResponse.headline}</h3>

          {/* Math / Direct Answer Box */}
          {customResponse.mathAnswer && (
            <div className="p-3 rounded-lg bg-primary/10 border border-primary/30 text-xs text-foreground font-medium leading-relaxed">
              <span className="text-primary font-bold">AI Answer: </span>
              {customResponse.mathAnswer}
            </div>
          )}
          <div className="space-y-1.5 pt-1">
            {customResponse.actionSteps.map((step, idx) => (
              <div key={idx} className="flex items-start gap-2 text-xs text-muted-foreground">
                <ArrowRight className="h-3.5 w-3.5 text-primary shrink-0 mt-0.5" />
                <span className="leading-relaxed">{step}</span>
              </div>
            ))}
          </div>

          {/* AI Action Bar */}
          <div className="mt-3 pt-3 border-t border-border/40 flex flex-col sm:flex-row items-center justify-between gap-2">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Brain className="h-4 w-4 text-primary shrink-0" />
              <span>AI Recommendation:</span>
              <span className="font-bold text-foreground capitalize px-2 py-0.5 rounded bg-primary/20 text-primary border border-primary/30 font-mono">
                {customResponse.suggestedType === "plan" ? "Active Plan" : "Priority Task"}
              </span>
            </div>

            <div className="flex items-center gap-2 w-full sm:w-auto">
              {customResponse.suggestedType === "plan" ? (
                <Button
                  size="sm"
                  onClick={() => handleAutoCreatePlan(customResponse)}
                  className="w-full sm:w-auto bg-primary/20 text-primary border border-primary/40 hover:bg-primary/30 text-xs font-semibold h-8 glow-blue"
                >
                  <CalendarIcon className="h-3.5 w-3.5 mr-1.5" />
                  + Convert & Add as Active Plan
                </Button>
              ) : (
                <Button
                  size="sm"
                  onClick={() => handleAutoCreateTask(customResponse)}
                  className="w-full sm:w-auto bg-secondary/20 text-secondary border border-secondary/40 hover:bg-secondary/30 text-xs font-semibold h-8"
                >
                  <Plus className="h-3.5 w-3.5 mr-1.5" />
                  + Convert & Add as Priority Task
                </Button>
              )}
            </div>
          </div>

          {createdNotice && (
            <div className="mt-2 p-2 rounded-lg bg-green-500/20 text-green-400 border border-green-500/30 text-xs font-bold text-center flex items-center justify-center gap-1.5 animate-in fade-in duration-200">
              <Check className="h-4 w-4 text-green-400" />
              {createdNotice}
            </div>
          )}
        </div>
      ) : (
        /* Tabs & Standard Overview */
        <div className="space-y-3">
          <div className="flex gap-1.5 overflow-x-auto pb-1">
            {[
              { id: "overview", label: "Smart Overview", icon: Sparkles },
              { id: "priority", label: "Recommended Focus", icon: Target },
              { id: "streaks", label: "Streak Momentum", icon: Flame },
              { id: "tips", label: "Genius Hacks", icon: Lightbulb },
            ].map((tab) => {
              const TabIcon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as InsightCategory)}
                  className={cn(
                    "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-all",
                    isActive
                      ? "bg-primary text-primary-foreground shadow-md"
                      : "glass text-muted-foreground hover:text-foreground"
                  )}
                >
                  <TabIcon className="h-3.5 w-3.5" />
                  {tab.label}
                </button>
              );
            })}
          </div>

          <div className="glass rounded-xl p-4 border border-border/40 relative">
            <div className="flex items-start gap-3">
              <div className="w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0 mt-0.5">
                <IconComponent className="h-5 w-5 text-primary" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap mb-1">
                  <h3 className="font-semibold text-sm text-foreground">{insightContent.title}</h3>
                  <span className={cn("px-2 py-0.5 rounded-full text-[10px] font-medium border", insightContent.badgeColor)}>
                    {insightContent.badge}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  {insightContent.description}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </GlassCard>
  );
}
